name: code-quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, mbstring
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Pint (dry-run)
        run: vendor/bin/pint --test

      - name: Rector (dry-run)
        run: vendor/bin/rector --dry-run

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress
